apiVersion: v1
kind: Pod
metadata:
  name: run-model-a01
spec:
  containers:
  - name: run-model-a01
    image: gcr.io/maintanence-scheduling/gke-test:1.2.0
    args:
    - julia
    - solve_ip.jl
    - A_09.json
    - out9.txt
  restartPolicy: Never
