apiVersion: v1
kind: Pod
metadata:
  name: run-model-a10
spec:
  containers:
  - name: run-model-a10
    image: gcr.io/maintanence-scheduling/gke-test:1.4.10
    args:
    - julia
    - solve_ip.jl
    - A_10.json
    - out10.txt
  restartPolicy: Never
