apiVersion: v1
kind: Pod
metadata:
  name: run-model-ex1
spec:
  containers:
  - name: run-model-ex1
    image: gcr.io/maintanence-scheduling/gke-test:latest
    args:
    - julia solve_ip.jl example1.json

