apiVersion: v1
kind: Pod
metadata:
  name: run-model-a07
spec:
  containers:
  - name: run-model-a07
    image: gcr.io/maintanence-scheduling/gke-test:1.2.7
    args:
    - julia
    - solve_ip.jl
    - A_07.json
    - out7.txt
  restartPolicy: Never
