apiVersion: v1
kind: Pod
metadata:
  name: run-model-a03
spec:
  containers:
  - name: run-model-a03
    image: gcr.io/maintanence-scheduling/gke-test:1.3.3
    args:
    - julia
    - solve_ip.jl
    - A_03.json
    - out03.txt
  restartPolicy: Never
