apiVersion: v1
kind: Pod
metadata:
  name: run-model-a12
spec:
  containers:
  - name: run-model-a12
    image: gcr.io/maintanence-scheduling/gke-test:1.4.12
    args:
    - julia
    - solve_ip.jl
    - A_12.json
    - out12.txt
  restartPolicy: Never
