apiVersion: v1
kind: Pod
metadata:
  name: run-model-a09
spec:
  containers:
  - name: run-model-a09
    image: gcr.io/maintanence-scheduling/gke-test:1.3.9
    args:
    - julia
    - solve_ip.jl
    - A_09.json
    - out09.txt
  restartPolicy: Never
